export const ordersPageColumns = [
  { field: "id", headerName: "ID", width: 70 },
  {
    field: "customerName",
    headerName: "Customer Name",
    width: 130,
  },
  { field: "products", headerName: "Products", width: 230, type: "array" },
  {
    field: "amount",
    headerName: "Amount",
    type: "number",
    width: 90,
  },
  {
    field: "address",
    headerName: "Address",
    type: "number",
  },
];

export const ordersPageRows = [
  {
    id: 1,
    customerName: "Snow",
    products: ["Garri", "Condom", "Paracetamol"],
    amount: 305,
    address: "Accra, Airpot City",
  },
  {
    id: 2,
    customerName: "Eric Bosomtwe",
    products: ["Beef", "Cheevon", "Mutton"],
    amount: 705,
    address: "Accra, East Legon",
  },
  {
    id: 3,
    customerName: "Maik Young",
    products: ["Selfie stick", "Turtle Neck", "Fake Chainz"],
    amount: 25,
    address: "Accra, Airpot City",
  },
  {
    id: 4,
    customerName: "Snow",
    products: ["Garri", "Condom", "Paracetamol"],
    amount: 305,
    address: "Accra, Airpot City",
  },
  {
    id: 5,
    customerName: "Eric Bosomtwe",
    products: ["Beef", "Cheevon", "Mutton"],
    amount: 705,
    address: "Accra, East Legon",
  },
  {
    id: 6,
    customerName: "Maik Young",
    products: ["Selfie stick", "Turtle Neck", "Fake Chainz"],
    amount: 25,
    address: "Accra, Airpot City",
  },
  {
    id: 7,
    customerName: "Eric Bosomtwe",
    products: ["Beef", "Cheevon", "Mutton"],
    amount: 705,
    address: "Accra, East Legon",
  },
  {
    id: 8,
    customerName: "Eric Bosomtwe",
    products: ["Beef", "Cheevon", "Mutton"],
    amount: 705,
    address: "Accra, East Legon",
  },
  {
    id: 9,
    customerName: "Maik Young",
    products: ["Selfie stick", "Turtle Neck", "Fake Chainz"],
    amount: 25,
    address: "Accra, Airpot City",
  },
  {
    id: 10,
    customerName: "Eric Bosomtwe",
    products: ["Beef", "Cheevon", "Mutton"],
    amount: 705,
    address: "Accra, East Legon",
  },
  {
    id: 11,
    customerName: "Maik Young",
    products: ["Selfie stick", "Turtle Neck", "Fake Chainz"],
    amount: 25,
    address: "Accra, Airpot City",
  },
];
